#!/usr/bin/env bash
#
# libguestfs Wrapper — self-contained wrapper to run libguestfs with minimal effort
# https://github.com/bkahlert/libguestfs
#
# MIT License
#
# Copyright (c) 2021 Dr. Björn Kahlert
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

declare wrapper_name=libguestfs
declare -a args=() wrapper_args=()
while (($#)); do
  case $1 in
    --${wrapper_name?}:*)
      wrapper_args+=("${1#--${wrapper_name?}:}")
      ;;
    *)
      args+=("$1")
      ;;
  esac
  shift
done
set -- "${args[@]}"

declare -a opts=()
opts+=("-e" "TESTING=${TESTING-}")
opts+=("-e" "RECORDING=${RECORDING-}")
opts+=("-e" "TERM=${TERM-}")

# Adds the given arguments to the opts array
opts() { eval 'opts+=("$@")'; }
[ ! -t 0 ] || opts+=("--interactive")
[ ! -t 1 ] || [ ! -t 2 ] || [ "${TERM-}" = dumb ] || opts+=("--tty")
[ ! -v LIBGUESTFS_ARGS ] || eval opts "$LIBGUESTFS_ARGS"
opts+=("${wrapper_args[@]}")
opts+=("--rm")
opts+=("--name" "$wrapper_name--$(head /dev/urandom | LC_ALL=C.UTF-8 tr -dc A-Za-z0-9 2>/dev/null | head -c 3)")
opts+=("${LIBGUESTFS_IMAGE:-bkahlert/libguestfs:${LIBGUESTFS_IMAGE_TAG:-latest}}")

docker run \
  -e DEBUG="${DEBUG-}" \
  -e TZ="$(date +"%Z")" \
  -e PUID="$(id -u)" \
  -e PGID="$(id -g)" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$PWD":"$PWD" \
  -w "$PWD" \
  "${opts[@]+"${opts[@]}"}" \
  "$@"
