#!/usr/bin/env bash

source <(curl -LfsS https://git.io/logr.sh)

declare disk && disk="$(find . -type f -iname "*.img" -not -path "*.data/*" | head -n 1)"
if [ ! -f "$disk" ]; then
  echo " $(tput setaf 1)✘$(tput sgr0)" "No image found." >&2
  echo "  " "Please run ${0##*/} in a directory containing an .img file." >&2
  exit 1
fi

headr "copyOut $disk"

declare -r source="${1:-/}"
if [ ! "${source:0:1}" = "/" ]; then
  echo " $(tput setaf 1)✘$(tput sgr0)" "$source must be absolute." >&2
  exit 1
fi

declare dest="${source%/*}"
dest="${disk%.*}.data/${dest#/}"

# Runs guestfs with the specified arguments.
guestfs() {
  if command -v guestfs >/dev/null; then
    command guestfs "$@"
  elif command -v libguestfsw >/dev/null; then
    command libguestfsw guestfs "$@"
  else
    curl -LfsS https://git.io/recordrw | "$SHELL" -s -- guestfs "$@"
  fi
}

guestfs \
  --ro \
  --add "$disk" \
  --inspector \
  <<COMMANDS
!mkdir -p "$dest"
-copy-out "$source" "$dest"
umount-all
exit
COMMANDS

[ "$(ls -A "$dest")" ] || rmdir -- "$dest"
