#!/usr/bin/env bash

# If a command list is passed via STDIN (see https://libguestfs.org/guestfish.1.html#from-shell-scripts):
# - redirect it to a file
# - pass it to guestfish as file (`-f`)
if [ ! -t 0 ]; then
  declare tmp
  tmp=$(mktemp "guestfish.XXXXXX")
  trap '[ ! -f "${tmp-}" ] || rm -- "$tmp"' EXIT
  cat - >"$tmp"
  set -- "$@" -f "$tmp"
fi

if command guestfish &>/dev/null; then
  command guestfish "$@"
elif command libguestfsw &>/dev/null; then
  command libguestfsw guestfish "$@"
else
  curl -LfsS https://git.io/libguestfsw | "$SHELL" -s -- guestfish "$@"
fi
