#!/bin/bash

set -euo pipefail

declare -a guestfish_args=("$@")
if [ ${#guestfish_args[@]} -eq 0 ]; then
    guestfish_args=("--help")
fi

docker run -i --rm --name "${0##*/}-$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 3 | head -n 1)" \
  -e PUID="$(id -u)" \
  -e PGID="$(id -g)" \
  -e LIBGUESTFS_DEBUG="${LIBGUESTFS_DEBUG:-0}" \
  -e LIBGUESTFS_TRACE="${LIBGUESTFS_TRACE:-0}" \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  "${LIBGUESTFS_IMAGE:-bkahlert/libguestfs}" \
  guestfish \
  "${guestfish_args[@]}"
