#!/bin/bash

set -euo pipefail

declare -a guestfish_args=("$@")
if [ ${#guestfish_args[@]} -eq 0 ]; then
    guestfish_args=("--help")
fi

docker run -i --rm --name "${0##*/}-$(tr -dc '[:alnum:]' < /dev/urandom 2>/dev/null | dd bs=4 count=1 2>/dev/null)" \
  -e PUID="$(id -u)" \
  -e PGID="$(id -g)" \
  -e LIBGUESTFS_DEBUG="${LIBGUESTFS_DEBUG:-0}" \
  -e LIBGUESTFS_TRACE="${LIBGUESTFS_TRACE:-0}" \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  "${LIBGUESTFS_IMAGE:-bkahlert/libguestfs}" \
  guestfish \
  "${guestfish_args[@]}"
