#!/usr/bin/env bash
# bashsupport disable=BP5004

if command virt-customize &>/dev/null; then
  command virt-customize "$@"
elif command libguestfsw &>/dev/null; then
  command libguestfsw virt-customize "$@"
else
  curl -LfsS https://git.io/libguestfsw | bash -s -- virt-customize "$@"
fi
