#!/bin/bash

set -euo pipefail

declare -a virt_customize_args=("$@")
if [ ${#virt_customize_args[@]} -eq 0 ]; then
    virt_customize_args=("--help")
fi

docker run -i --rm --name "${0##*/}-$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom 2>/dev/null | head -c 3 || true)" \
  -e PUID="$(id -u)" \
  -e PGID="$(id -g)" \
  -e LIBGUESTFS_DEBUG="${LIBGUESTFS_DEBUG:-0}" \
  -e LIBGUESTFS_TRACE="${LIBGUESTFS_TRACE:-0}" \
  -v "$PWD:$PWD" \
  -w "$PWD" \
  "${LIBGUESTFS_IMAGE:-bkahlert/libguestfs}" \
  virt-customize \
  "${virt_customize_args[@]}"
