#!/usr/bin/env bash

if command -v virt-builder >/dev/null; then
  command virt-builder "$@"
elif command -v libguestfsw >/dev/null; then
  command libguestfsw virt-builder "$@"
else
  curl -LfsS https://git.io/recordrw | "$SHELL" -s -- virt-builder "$@"
fi
