name: test

on:
  push:
    branches: ['master']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['master']
    paths-ignore: ['**.md']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run tests
        run: |
          chmod +x test/test-container
          ./test/test-container
