name: test

on:
  push:
    branches: ['master']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['master']
    paths-ignore: ['**.md']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=build_tag::test
          echo ::set-output name=test_reports::build/test-reports

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Build
#        uses: docker/bake-action@v1
#        with:
#          targets: image-local
#        env:
#          DEFAULT_TAG: ${{ steps.prep.outputs.build_tag }}

      - name: Run tests
        run: |
          chmod +x run_tests
          ./run_tests test \
            --env BUILD_TAG="${{ steps.prep.outputs.build_tag }}" \
            --output "${{ steps.prep.outputs.test_reports }}"

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-reports
          path: ${{ steps.prep.outputs.test_reports }}/*.xml
